/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XatuRouteImport } from './routes/xatu'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as EthereumRouteImport } from './routes/ethereum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XatuDataIndexRouteImport } from './routes/xatu-data/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as XatuLocallyBuiltBlocksRouteImport } from './routes/xatu/locally-built-blocks'
import { Route as XatuGeographicalChecklistRouteImport } from './routes/xatu/geographical-checklist'
import { Route as XatuForkReadinessRouteImport } from './routes/xatu/fork-readiness'
import { Route as XatuContributorsRouteImport } from './routes/xatu/contributors'
import { Route as XatuDataGeographicalChecklistRouteImport } from './routes/xatu-data/geographical-checklist'
import { Route as XatuDataForkReadinessRouteImport } from './routes/xatu-data/fork-readiness'
import { Route as ExperimentsLiveSlotsRouteImport } from './routes/experiments/live-slots'
import { Route as ExperimentsBlockProductionFlowRouteImport } from './routes/experiments/block-production-flow'
import { Route as EthereumValidatorsRouteImport } from './routes/ethereum/validators'
import { Route as EthereumSlotsRouteImport } from './routes/ethereum/slots'
import { Route as EthereumLiveRouteImport } from './routes/ethereum/live'
import { Route as EthereumForksRouteImport } from './routes/ethereum/forks'
import { Route as EthereumExecutionRouteImport } from './routes/ethereum/execution'
import { Route as EthereumEpochsRouteImport } from './routes/ethereum/epochs'
import { Route as EthereumEntitiesRouteImport } from './routes/ethereum/entities'
import { Route as EthereumDataAvailabilityRouteImport } from './routes/ethereum/data-availability'
import { Route as EthereumContractsRouteImport } from './routes/ethereum/contracts'
import { Route as EthereumConsensusRouteImport } from './routes/ethereum/consensus'
import { Route as BeaconLocallyBuiltBlocksRouteImport } from './routes/beacon/locally-built-blocks'
import { Route as XatuContributorsIndexRouteImport } from './routes/xatu/contributors/index'
import { Route as EthereumValidatorsIndexRouteImport } from './routes/ethereum/validators/index'
import { Route as EthereumSlotsIndexRouteImport } from './routes/ethereum/slots/index'
import { Route as EthereumForksIndexRouteImport } from './routes/ethereum/forks/index'
import { Route as EthereumEpochsIndexRouteImport } from './routes/ethereum/epochs/index'
import { Route as EthereumEntitiesIndexRouteImport } from './routes/ethereum/entities/index'
import { Route as EthereumContractsIndexRouteImport } from './routes/ethereum/contracts/index'
import { Route as XatuContributorsIdRouteImport } from './routes/xatu/contributors/$id'
import { Route as EthereumSlotsSlotRouteImport } from './routes/ethereum/slots/$slot'
import { Route as EthereumForksForkRouteImport } from './routes/ethereum/forks/$fork'
import { Route as EthereumExecutionTimingsRouteImport } from './routes/ethereum/execution/timings'
import { Route as EthereumExecutionStateGrowthRouteImport } from './routes/ethereum/execution/state-growth'
import { Route as EthereumExecutionStateExpiryRouteImport } from './routes/ethereum/execution/state-expiry'
import { Route as EthereumExecutionPayloadsRouteImport } from './routes/ethereum/execution/payloads'
import { Route as EthereumExecutionOverviewRouteImport } from './routes/ethereum/execution/overview'
import { Route as EthereumExecutionGasProfilerRouteImport } from './routes/ethereum/execution/gas-profiler'
import { Route as EthereumEpochsEpochRouteImport } from './routes/ethereum/epochs/$epoch'
import { Route as EthereumEntitiesEntityRouteImport } from './routes/ethereum/entities/$entity'
import { Route as EthereumDataAvailabilityProbesRouteImport } from './routes/ethereum/data-availability/probes'
import { Route as EthereumDataAvailabilityCustodyRouteImport } from './routes/ethereum/data-availability/custody'
import { Route as EthereumContractsAddressRouteImport } from './routes/ethereum/contracts/$address'
import { Route as EthereumConsensusOverviewRouteImport } from './routes/ethereum/consensus/overview'
import { Route as EthereumConsensusFastConfirmationRouteImport } from './routes/ethereum/consensus/fast-confirmation'
import { Route as BeaconSlotLiveRouteImport } from './routes/beacon/slot/live'
import { Route as BeaconBlockProductionLiveRouteImport } from './routes/beacon/block-production/live'
import { Route as EthereumExecutionTimingsIndexRouteImport } from './routes/ethereum/execution/timings/index'
import { Route as EthereumExecutionPayloadsIndexRouteImport } from './routes/ethereum/execution/payloads/index'
import { Route as EthereumExecutionGasProfilerIndexRouteImport } from './routes/ethereum/execution/gas-profiler/index'
import { Route as EthereumDataAvailabilityProbesIndexRouteImport } from './routes/ethereum/data-availability/probes/index'
import { Route as EthereumDataAvailabilityCustodyIndexRouteImport } from './routes/ethereum/data-availability/custody/index'
import { Route as EthereumExecutionGasProfilerSimulateRouteImport } from './routes/ethereum/execution/gas-profiler/simulate'
import { Route as EthereumExecutionGasProfilerTxTxHashRouteImport } from './routes/ethereum/execution/gas-profiler/tx.$txHash'
import { Route as EthereumExecutionGasProfilerBlockBlockNumberRouteImport } from './routes/ethereum/execution/gas-profiler/block.$blockNumber'
import { Route as EthereumExecutionGasProfilerTxTxHashCallCallIdRouteImport } from './routes/ethereum/execution/gas-profiler/tx.$txHash_.call.$callId'

const XatuRoute = XatuRouteImport.update({
  id: '/xatu',
  path: '/xatu',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const EthereumRoute = EthereumRouteImport.update({
  id: '/ethereum',
  path: '/ethereum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XatuDataIndexRoute = XatuDataIndexRouteImport.update({
  id: '/xatu-data/',
  path: '/xatu-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const XatuLocallyBuiltBlocksRoute = XatuLocallyBuiltBlocksRouteImport.update({
  id: '/locally-built-blocks',
  path: '/locally-built-blocks',
  getParentRoute: () => XatuRoute,
} as any)
const XatuGeographicalChecklistRoute =
  XatuGeographicalChecklistRouteImport.update({
    id: '/geographical-checklist',
    path: '/geographical-checklist',
    getParentRoute: () => XatuRoute,
  } as any)
const XatuForkReadinessRoute = XatuForkReadinessRouteImport.update({
  id: '/fork-readiness',
  path: '/fork-readiness',
  getParentRoute: () => XatuRoute,
} as any)
const XatuContributorsRoute = XatuContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => XatuRoute,
} as any)
const XatuDataGeographicalChecklistRoute =
  XatuDataGeographicalChecklistRouteImport.update({
    id: '/xatu-data/geographical-checklist',
    path: '/xatu-data/geographical-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const XatuDataForkReadinessRoute = XatuDataForkReadinessRouteImport.update({
  id: '/xatu-data/fork-readiness',
  path: '/xatu-data/fork-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsLiveSlotsRoute = ExperimentsLiveSlotsRouteImport.update({
  id: '/live-slots',
  path: '/live-slots',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsBlockProductionFlowRoute =
  ExperimentsBlockProductionFlowRouteImport.update({
    id: '/block-production-flow',
    path: '/block-production-flow',
    getParentRoute: () => ExperimentsRoute,
  } as any)
const EthereumValidatorsRoute = EthereumValidatorsRouteImport.update({
  id: '/validators',
  path: '/validators',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumSlotsRoute = EthereumSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumLiveRoute = EthereumLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumForksRoute = EthereumForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumExecutionRoute = EthereumExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumEpochsRoute = EthereumEpochsRouteImport.update({
  id: '/epochs',
  path: '/epochs',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumEntitiesRoute = EthereumEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumDataAvailabilityRoute =
  EthereumDataAvailabilityRouteImport.update({
    id: '/data-availability',
    path: '/data-availability',
    getParentRoute: () => EthereumRoute,
  } as any)
const EthereumContractsRoute = EthereumContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => EthereumRoute,
} as any)
const EthereumConsensusRoute = EthereumConsensusRouteImport.update({
  id: '/consensus',
  path: '/consensus',
  getParentRoute: () => EthereumRoute,
} as any)
const BeaconLocallyBuiltBlocksRoute =
  BeaconLocallyBuiltBlocksRouteImport.update({
    id: '/beacon/locally-built-blocks',
    path: '/beacon/locally-built-blocks',
    getParentRoute: () => rootRouteImport,
  } as any)
const XatuContributorsIndexRoute = XatuContributorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => XatuContributorsRoute,
} as any)
const EthereumValidatorsIndexRoute = EthereumValidatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumValidatorsRoute,
} as any)
const EthereumSlotsIndexRoute = EthereumSlotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumSlotsRoute,
} as any)
const EthereumForksIndexRoute = EthereumForksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumForksRoute,
} as any)
const EthereumEpochsIndexRoute = EthereumEpochsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumEpochsRoute,
} as any)
const EthereumEntitiesIndexRoute = EthereumEntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumEntitiesRoute,
} as any)
const EthereumContractsIndexRoute = EthereumContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumContractsRoute,
} as any)
const XatuContributorsIdRoute = XatuContributorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => XatuContributorsRoute,
} as any)
const EthereumSlotsSlotRoute = EthereumSlotsSlotRouteImport.update({
  id: '/$slot',
  path: '/$slot',
  getParentRoute: () => EthereumSlotsRoute,
} as any)
const EthereumForksForkRoute = EthereumForksForkRouteImport.update({
  id: '/$fork',
  path: '/$fork',
  getParentRoute: () => EthereumForksRoute,
} as any)
const EthereumExecutionTimingsRoute =
  EthereumExecutionTimingsRouteImport.update({
    id: '/timings',
    path: '/timings',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumExecutionStateGrowthRoute =
  EthereumExecutionStateGrowthRouteImport.update({
    id: '/state-growth',
    path: '/state-growth',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumExecutionStateExpiryRoute =
  EthereumExecutionStateExpiryRouteImport.update({
    id: '/state-expiry',
    path: '/state-expiry',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumExecutionPayloadsRoute =
  EthereumExecutionPayloadsRouteImport.update({
    id: '/payloads',
    path: '/payloads',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumExecutionOverviewRoute =
  EthereumExecutionOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumExecutionGasProfilerRoute =
  EthereumExecutionGasProfilerRouteImport.update({
    id: '/gas-profiler',
    path: '/gas-profiler',
    getParentRoute: () => EthereumExecutionRoute,
  } as any)
const EthereumEpochsEpochRoute = EthereumEpochsEpochRouteImport.update({
  id: '/$epoch',
  path: '/$epoch',
  getParentRoute: () => EthereumEpochsRoute,
} as any)
const EthereumEntitiesEntityRoute = EthereumEntitiesEntityRouteImport.update({
  id: '/$entity',
  path: '/$entity',
  getParentRoute: () => EthereumEntitiesRoute,
} as any)
const EthereumDataAvailabilityProbesRoute =
  EthereumDataAvailabilityProbesRouteImport.update({
    id: '/probes',
    path: '/probes',
    getParentRoute: () => EthereumDataAvailabilityRoute,
  } as any)
const EthereumDataAvailabilityCustodyRoute =
  EthereumDataAvailabilityCustodyRouteImport.update({
    id: '/custody',
    path: '/custody',
    getParentRoute: () => EthereumDataAvailabilityRoute,
  } as any)
const EthereumContractsAddressRoute =
  EthereumContractsAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => EthereumContractsRoute,
  } as any)
const EthereumConsensusOverviewRoute =
  EthereumConsensusOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => EthereumConsensusRoute,
  } as any)
const EthereumConsensusFastConfirmationRoute =
  EthereumConsensusFastConfirmationRouteImport.update({
    id: '/fast-confirmation',
    path: '/fast-confirmation',
    getParentRoute: () => EthereumConsensusRoute,
  } as any)
const BeaconSlotLiveRoute = BeaconSlotLiveRouteImport.update({
  id: '/beacon/slot/live',
  path: '/beacon/slot/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaconBlockProductionLiveRoute =
  BeaconBlockProductionLiveRouteImport.update({
    id: '/beacon/block-production/live',
    path: '/beacon/block-production/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const EthereumExecutionTimingsIndexRoute =
  EthereumExecutionTimingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumExecutionTimingsRoute,
  } as any)
const EthereumExecutionPayloadsIndexRoute =
  EthereumExecutionPayloadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumExecutionPayloadsRoute,
  } as any)
const EthereumExecutionGasProfilerIndexRoute =
  EthereumExecutionGasProfilerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumExecutionGasProfilerRoute,
  } as any)
const EthereumDataAvailabilityProbesIndexRoute =
  EthereumDataAvailabilityProbesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumDataAvailabilityProbesRoute,
  } as any)
const EthereumDataAvailabilityCustodyIndexRoute =
  EthereumDataAvailabilityCustodyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EthereumDataAvailabilityCustodyRoute,
  } as any)
const EthereumExecutionGasProfilerSimulateRoute =
  EthereumExecutionGasProfilerSimulateRouteImport.update({
    id: '/simulate',
    path: '/simulate',
    getParentRoute: () => EthereumExecutionGasProfilerRoute,
  } as any)
const EthereumExecutionGasProfilerTxTxHashRoute =
  EthereumExecutionGasProfilerTxTxHashRouteImport.update({
    id: '/tx/$txHash',
    path: '/tx/$txHash',
    getParentRoute: () => EthereumExecutionGasProfilerRoute,
  } as any)
const EthereumExecutionGasProfilerBlockBlockNumberRoute =
  EthereumExecutionGasProfilerBlockBlockNumberRouteImport.update({
    id: '/block/$blockNumber',
    path: '/block/$blockNumber',
    getParentRoute: () => EthereumExecutionGasProfilerRoute,
  } as any)
const EthereumExecutionGasProfilerTxTxHashCallCallIdRoute =
  EthereumExecutionGasProfilerTxTxHashCallCallIdRouteImport.update({
    id: '/tx/$txHash_/call/$callId',
    path: '/tx/$txHash/call/$callId',
    getParentRoute: () => EthereumExecutionGasProfilerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/consensus': typeof EthereumConsensusRouteWithChildren
  '/ethereum/contracts': typeof EthereumContractsRouteWithChildren
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/entities': typeof EthereumEntitiesRouteWithChildren
  '/ethereum/epochs': typeof EthereumEpochsRouteWithChildren
  '/ethereum/execution': typeof EthereumExecutionRouteWithChildren
  '/ethereum/forks': typeof EthereumForksRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/ethereum/slots': typeof EthereumSlotsRouteWithChildren
  '/ethereum/validators': typeof EthereumValidatorsRouteWithChildren
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu-data/': typeof XatuDataIndexRoute
  '/beacon/block-production/live': typeof BeaconBlockProductionLiveRoute
  '/beacon/slot/live': typeof BeaconSlotLiveRoute
  '/ethereum/consensus/fast-confirmation': typeof EthereumConsensusFastConfirmationRoute
  '/ethereum/consensus/overview': typeof EthereumConsensusOverviewRoute
  '/ethereum/contracts/$address': typeof EthereumContractsAddressRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyRouteWithChildren
  '/ethereum/data-availability/probes': typeof EthereumDataAvailabilityProbesRouteWithChildren
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/execution/gas-profiler': typeof EthereumExecutionGasProfilerRouteWithChildren
  '/ethereum/execution/overview': typeof EthereumExecutionOverviewRoute
  '/ethereum/execution/payloads': typeof EthereumExecutionPayloadsRouteWithChildren
  '/ethereum/execution/state-expiry': typeof EthereumExecutionStateExpiryRoute
  '/ethereum/execution/state-growth': typeof EthereumExecutionStateGrowthRoute
  '/ethereum/execution/timings': typeof EthereumExecutionTimingsRouteWithChildren
  '/ethereum/forks/$fork': typeof EthereumForksForkRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/contracts/': typeof EthereumContractsIndexRoute
  '/ethereum/entities/': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs/': typeof EthereumEpochsIndexRoute
  '/ethereum/forks/': typeof EthereumForksIndexRoute
  '/ethereum/slots/': typeof EthereumSlotsIndexRoute
  '/ethereum/validators/': typeof EthereumValidatorsIndexRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
  '/ethereum/execution/gas-profiler/simulate': typeof EthereumExecutionGasProfilerSimulateRoute
  '/ethereum/data-availability/custody/': typeof EthereumDataAvailabilityCustodyIndexRoute
  '/ethereum/data-availability/probes/': typeof EthereumDataAvailabilityProbesIndexRoute
  '/ethereum/execution/gas-profiler/': typeof EthereumExecutionGasProfilerIndexRoute
  '/ethereum/execution/payloads/': typeof EthereumExecutionPayloadsIndexRoute
  '/ethereum/execution/timings/': typeof EthereumExecutionTimingsIndexRoute
  '/ethereum/execution/gas-profiler/block/$blockNumber': typeof EthereumExecutionGasProfilerBlockBlockNumberRoute
  '/ethereum/execution/gas-profiler/tx/$txHash': typeof EthereumExecutionGasProfilerTxTxHashRoute
  '/ethereum/execution/gas-profiler/tx/$txHash/call/$callId': typeof EthereumExecutionGasProfilerTxTxHashCallCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/consensus': typeof EthereumConsensusRouteWithChildren
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/execution': typeof EthereumExecutionRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/xatu-data': typeof XatuDataIndexRoute
  '/beacon/block-production/live': typeof BeaconBlockProductionLiveRoute
  '/beacon/slot/live': typeof BeaconSlotLiveRoute
  '/ethereum/consensus/fast-confirmation': typeof EthereumConsensusFastConfirmationRoute
  '/ethereum/consensus/overview': typeof EthereumConsensusOverviewRoute
  '/ethereum/contracts/$address': typeof EthereumContractsAddressRoute
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/execution/overview': typeof EthereumExecutionOverviewRoute
  '/ethereum/execution/state-expiry': typeof EthereumExecutionStateExpiryRoute
  '/ethereum/execution/state-growth': typeof EthereumExecutionStateGrowthRoute
  '/ethereum/forks/$fork': typeof EthereumForksForkRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/contracts': typeof EthereumContractsIndexRoute
  '/ethereum/entities': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs': typeof EthereumEpochsIndexRoute
  '/ethereum/forks': typeof EthereumForksIndexRoute
  '/ethereum/slots': typeof EthereumSlotsIndexRoute
  '/ethereum/validators': typeof EthereumValidatorsIndexRoute
  '/xatu/contributors': typeof XatuContributorsIndexRoute
  '/ethereum/execution/gas-profiler/simulate': typeof EthereumExecutionGasProfilerSimulateRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyIndexRoute
  '/ethereum/data-availability/probes': typeof EthereumDataAvailabilityProbesIndexRoute
  '/ethereum/execution/gas-profiler': typeof EthereumExecutionGasProfilerIndexRoute
  '/ethereum/execution/payloads': typeof EthereumExecutionPayloadsIndexRoute
  '/ethereum/execution/timings': typeof EthereumExecutionTimingsIndexRoute
  '/ethereum/execution/gas-profiler/block/$blockNumber': typeof EthereumExecutionGasProfilerBlockBlockNumberRoute
  '/ethereum/execution/gas-profiler/tx/$txHash': typeof EthereumExecutionGasProfilerTxTxHashRoute
  '/ethereum/execution/gas-profiler/tx/$txHash/call/$callId': typeof EthereumExecutionGasProfilerTxTxHashCallCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ethereum': typeof EthereumRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/xatu': typeof XatuRouteWithChildren
  '/beacon/locally-built-blocks': typeof BeaconLocallyBuiltBlocksRoute
  '/ethereum/consensus': typeof EthereumConsensusRouteWithChildren
  '/ethereum/contracts': typeof EthereumContractsRouteWithChildren
  '/ethereum/data-availability': typeof EthereumDataAvailabilityRouteWithChildren
  '/ethereum/entities': typeof EthereumEntitiesRouteWithChildren
  '/ethereum/epochs': typeof EthereumEpochsRouteWithChildren
  '/ethereum/execution': typeof EthereumExecutionRouteWithChildren
  '/ethereum/forks': typeof EthereumForksRouteWithChildren
  '/ethereum/live': typeof EthereumLiveRoute
  '/ethereum/slots': typeof EthereumSlotsRouteWithChildren
  '/ethereum/validators': typeof EthereumValidatorsRouteWithChildren
  '/experiments/block-production-flow': typeof ExperimentsBlockProductionFlowRoute
  '/experiments/live-slots': typeof ExperimentsLiveSlotsRoute
  '/xatu-data/fork-readiness': typeof XatuDataForkReadinessRoute
  '/xatu-data/geographical-checklist': typeof XatuDataGeographicalChecklistRoute
  '/xatu/contributors': typeof XatuContributorsRouteWithChildren
  '/xatu/fork-readiness': typeof XatuForkReadinessRoute
  '/xatu/geographical-checklist': typeof XatuGeographicalChecklistRoute
  '/xatu/locally-built-blocks': typeof XatuLocallyBuiltBlocksRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/xatu-data/': typeof XatuDataIndexRoute
  '/beacon/block-production/live': typeof BeaconBlockProductionLiveRoute
  '/beacon/slot/live': typeof BeaconSlotLiveRoute
  '/ethereum/consensus/fast-confirmation': typeof EthereumConsensusFastConfirmationRoute
  '/ethereum/consensus/overview': typeof EthereumConsensusOverviewRoute
  '/ethereum/contracts/$address': typeof EthereumContractsAddressRoute
  '/ethereum/data-availability/custody': typeof EthereumDataAvailabilityCustodyRouteWithChildren
  '/ethereum/data-availability/probes': typeof EthereumDataAvailabilityProbesRouteWithChildren
  '/ethereum/entities/$entity': typeof EthereumEntitiesEntityRoute
  '/ethereum/epochs/$epoch': typeof EthereumEpochsEpochRoute
  '/ethereum/execution/gas-profiler': typeof EthereumExecutionGasProfilerRouteWithChildren
  '/ethereum/execution/overview': typeof EthereumExecutionOverviewRoute
  '/ethereum/execution/payloads': typeof EthereumExecutionPayloadsRouteWithChildren
  '/ethereum/execution/state-expiry': typeof EthereumExecutionStateExpiryRoute
  '/ethereum/execution/state-growth': typeof EthereumExecutionStateGrowthRoute
  '/ethereum/execution/timings': typeof EthereumExecutionTimingsRouteWithChildren
  '/ethereum/forks/$fork': typeof EthereumForksForkRoute
  '/ethereum/slots/$slot': typeof EthereumSlotsSlotRoute
  '/xatu/contributors/$id': typeof XatuContributorsIdRoute
  '/ethereum/contracts/': typeof EthereumContractsIndexRoute
  '/ethereum/entities/': typeof EthereumEntitiesIndexRoute
  '/ethereum/epochs/': typeof EthereumEpochsIndexRoute
  '/ethereum/forks/': typeof EthereumForksIndexRoute
  '/ethereum/slots/': typeof EthereumSlotsIndexRoute
  '/ethereum/validators/': typeof EthereumValidatorsIndexRoute
  '/xatu/contributors/': typeof XatuContributorsIndexRoute
  '/ethereum/execution/gas-profiler/simulate': typeof EthereumExecutionGasProfilerSimulateRoute
  '/ethereum/data-availability/custody/': typeof EthereumDataAvailabilityCustodyIndexRoute
  '/ethereum/data-availability/probes/': typeof EthereumDataAvailabilityProbesIndexRoute
  '/ethereum/execution/gas-profiler/': typeof EthereumExecutionGasProfilerIndexRoute
  '/ethereum/execution/payloads/': typeof EthereumExecutionPayloadsIndexRoute
  '/ethereum/execution/timings/': typeof EthereumExecutionTimingsIndexRoute
  '/ethereum/execution/gas-profiler/block/$blockNumber': typeof EthereumExecutionGasProfilerBlockBlockNumberRoute
  '/ethereum/execution/gas-profiler/tx/$txHash': typeof EthereumExecutionGasProfilerTxTxHashRoute
  '/ethereum/execution/gas-profiler/tx/$txHash_/call/$callId': typeof EthereumExecutionGasProfilerTxTxHashCallCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/consensus'
    | '/ethereum/contracts'
    | '/ethereum/data-availability'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/execution'
    | '/ethereum/forks'
    | '/ethereum/live'
    | '/ethereum/slots'
    | '/ethereum/validators'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu-data/'
    | '/beacon/block-production/live'
    | '/beacon/slot/live'
    | '/ethereum/consensus/fast-confirmation'
    | '/ethereum/consensus/overview'
    | '/ethereum/contracts/$address'
    | '/ethereum/data-availability/custody'
    | '/ethereum/data-availability/probes'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/execution/gas-profiler'
    | '/ethereum/execution/overview'
    | '/ethereum/execution/payloads'
    | '/ethereum/execution/state-expiry'
    | '/ethereum/execution/state-growth'
    | '/ethereum/execution/timings'
    | '/ethereum/forks/$fork'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/contracts/'
    | '/ethereum/entities/'
    | '/ethereum/epochs/'
    | '/ethereum/forks/'
    | '/ethereum/slots/'
    | '/ethereum/validators/'
    | '/xatu/contributors/'
    | '/ethereum/execution/gas-profiler/simulate'
    | '/ethereum/data-availability/custody/'
    | '/ethereum/data-availability/probes/'
    | '/ethereum/execution/gas-profiler/'
    | '/ethereum/execution/payloads/'
    | '/ethereum/execution/timings/'
    | '/ethereum/execution/gas-profiler/block/$blockNumber'
    | '/ethereum/execution/gas-profiler/tx/$txHash'
    | '/ethereum/execution/gas-profiler/tx/$txHash/call/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ethereum'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/consensus'
    | '/ethereum/data-availability'
    | '/ethereum/execution'
    | '/ethereum/live'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments'
    | '/xatu-data'
    | '/beacon/block-production/live'
    | '/beacon/slot/live'
    | '/ethereum/consensus/fast-confirmation'
    | '/ethereum/consensus/overview'
    | '/ethereum/contracts/$address'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/execution/overview'
    | '/ethereum/execution/state-expiry'
    | '/ethereum/execution/state-growth'
    | '/ethereum/forks/$fork'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/contracts'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/forks'
    | '/ethereum/slots'
    | '/ethereum/validators'
    | '/xatu/contributors'
    | '/ethereum/execution/gas-profiler/simulate'
    | '/ethereum/data-availability/custody'
    | '/ethereum/data-availability/probes'
    | '/ethereum/execution/gas-profiler'
    | '/ethereum/execution/payloads'
    | '/ethereum/execution/timings'
    | '/ethereum/execution/gas-profiler/block/$blockNumber'
    | '/ethereum/execution/gas-profiler/tx/$txHash'
    | '/ethereum/execution/gas-profiler/tx/$txHash/call/$callId'
  id:
    | '__root__'
    | '/'
    | '/ethereum'
    | '/experiments'
    | '/xatu'
    | '/beacon/locally-built-blocks'
    | '/ethereum/consensus'
    | '/ethereum/contracts'
    | '/ethereum/data-availability'
    | '/ethereum/entities'
    | '/ethereum/epochs'
    | '/ethereum/execution'
    | '/ethereum/forks'
    | '/ethereum/live'
    | '/ethereum/slots'
    | '/ethereum/validators'
    | '/experiments/block-production-flow'
    | '/experiments/live-slots'
    | '/xatu-data/fork-readiness'
    | '/xatu-data/geographical-checklist'
    | '/xatu/contributors'
    | '/xatu/fork-readiness'
    | '/xatu/geographical-checklist'
    | '/xatu/locally-built-blocks'
    | '/experiments/'
    | '/xatu-data/'
    | '/beacon/block-production/live'
    | '/beacon/slot/live'
    | '/ethereum/consensus/fast-confirmation'
    | '/ethereum/consensus/overview'
    | '/ethereum/contracts/$address'
    | '/ethereum/data-availability/custody'
    | '/ethereum/data-availability/probes'
    | '/ethereum/entities/$entity'
    | '/ethereum/epochs/$epoch'
    | '/ethereum/execution/gas-profiler'
    | '/ethereum/execution/overview'
    | '/ethereum/execution/payloads'
    | '/ethereum/execution/state-expiry'
    | '/ethereum/execution/state-growth'
    | '/ethereum/execution/timings'
    | '/ethereum/forks/$fork'
    | '/ethereum/slots/$slot'
    | '/xatu/contributors/$id'
    | '/ethereum/contracts/'
    | '/ethereum/entities/'
    | '/ethereum/epochs/'
    | '/ethereum/forks/'
    | '/ethereum/slots/'
    | '/ethereum/validators/'
    | '/xatu/contributors/'
    | '/ethereum/execution/gas-profiler/simulate'
    | '/ethereum/data-availability/custody/'
    | '/ethereum/data-availability/probes/'
    | '/ethereum/execution/gas-profiler/'
    | '/ethereum/execution/payloads/'
    | '/ethereum/execution/timings/'
    | '/ethereum/execution/gas-profiler/block/$blockNumber'
    | '/ethereum/execution/gas-profiler/tx/$txHash'
    | '/ethereum/execution/gas-profiler/tx/$txHash_/call/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EthereumRoute: typeof EthereumRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  XatuRoute: typeof XatuRouteWithChildren
  BeaconLocallyBuiltBlocksRoute: typeof BeaconLocallyBuiltBlocksRoute
  XatuDataForkReadinessRoute: typeof XatuDataForkReadinessRoute
  XatuDataGeographicalChecklistRoute: typeof XatuDataGeographicalChecklistRoute
  XatuDataIndexRoute: typeof XatuDataIndexRoute
  BeaconBlockProductionLiveRoute: typeof BeaconBlockProductionLiveRoute
  BeaconSlotLiveRoute: typeof BeaconSlotLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xatu': {
      id: '/xatu'
      path: '/xatu'
      fullPath: '/xatu'
      preLoaderRoute: typeof XatuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethereum': {
      id: '/ethereum'
      path: '/ethereum'
      fullPath: '/ethereum'
      preLoaderRoute: typeof EthereumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu-data/': {
      id: '/xatu-data/'
      path: '/xatu-data'
      fullPath: '/xatu-data/'
      preLoaderRoute: typeof XatuDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/xatu/locally-built-blocks': {
      id: '/xatu/locally-built-blocks'
      path: '/locally-built-blocks'
      fullPath: '/xatu/locally-built-blocks'
      preLoaderRoute: typeof XatuLocallyBuiltBlocksRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/geographical-checklist': {
      id: '/xatu/geographical-checklist'
      path: '/geographical-checklist'
      fullPath: '/xatu/geographical-checklist'
      preLoaderRoute: typeof XatuGeographicalChecklistRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/fork-readiness': {
      id: '/xatu/fork-readiness'
      path: '/fork-readiness'
      fullPath: '/xatu/fork-readiness'
      preLoaderRoute: typeof XatuForkReadinessRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu/contributors': {
      id: '/xatu/contributors'
      path: '/contributors'
      fullPath: '/xatu/contributors'
      preLoaderRoute: typeof XatuContributorsRouteImport
      parentRoute: typeof XatuRoute
    }
    '/xatu-data/geographical-checklist': {
      id: '/xatu-data/geographical-checklist'
      path: '/xatu-data/geographical-checklist'
      fullPath: '/xatu-data/geographical-checklist'
      preLoaderRoute: typeof XatuDataGeographicalChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu-data/fork-readiness': {
      id: '/xatu-data/fork-readiness'
      path: '/xatu-data/fork-readiness'
      fullPath: '/xatu-data/fork-readiness'
      preLoaderRoute: typeof XatuDataForkReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/live-slots': {
      id: '/experiments/live-slots'
      path: '/live-slots'
      fullPath: '/experiments/live-slots'
      preLoaderRoute: typeof ExperimentsLiveSlotsRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/block-production-flow': {
      id: '/experiments/block-production-flow'
      path: '/block-production-flow'
      fullPath: '/experiments/block-production-flow'
      preLoaderRoute: typeof ExperimentsBlockProductionFlowRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/ethereum/validators': {
      id: '/ethereum/validators'
      path: '/validators'
      fullPath: '/ethereum/validators'
      preLoaderRoute: typeof EthereumValidatorsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/slots': {
      id: '/ethereum/slots'
      path: '/slots'
      fullPath: '/ethereum/slots'
      preLoaderRoute: typeof EthereumSlotsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/live': {
      id: '/ethereum/live'
      path: '/live'
      fullPath: '/ethereum/live'
      preLoaderRoute: typeof EthereumLiveRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/forks': {
      id: '/ethereum/forks'
      path: '/forks'
      fullPath: '/ethereum/forks'
      preLoaderRoute: typeof EthereumForksRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/execution': {
      id: '/ethereum/execution'
      path: '/execution'
      fullPath: '/ethereum/execution'
      preLoaderRoute: typeof EthereumExecutionRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/epochs': {
      id: '/ethereum/epochs'
      path: '/epochs'
      fullPath: '/ethereum/epochs'
      preLoaderRoute: typeof EthereumEpochsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/entities': {
      id: '/ethereum/entities'
      path: '/entities'
      fullPath: '/ethereum/entities'
      preLoaderRoute: typeof EthereumEntitiesRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/data-availability': {
      id: '/ethereum/data-availability'
      path: '/data-availability'
      fullPath: '/ethereum/data-availability'
      preLoaderRoute: typeof EthereumDataAvailabilityRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/contracts': {
      id: '/ethereum/contracts'
      path: '/contracts'
      fullPath: '/ethereum/contracts'
      preLoaderRoute: typeof EthereumContractsRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/ethereum/consensus': {
      id: '/ethereum/consensus'
      path: '/consensus'
      fullPath: '/ethereum/consensus'
      preLoaderRoute: typeof EthereumConsensusRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/beacon/locally-built-blocks': {
      id: '/beacon/locally-built-blocks'
      path: '/beacon/locally-built-blocks'
      fullPath: '/beacon/locally-built-blocks'
      preLoaderRoute: typeof BeaconLocallyBuiltBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatu/contributors/': {
      id: '/xatu/contributors/'
      path: '/'
      fullPath: '/xatu/contributors/'
      preLoaderRoute: typeof XatuContributorsIndexRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
    '/ethereum/validators/': {
      id: '/ethereum/validators/'
      path: '/'
      fullPath: '/ethereum/validators/'
      preLoaderRoute: typeof EthereumValidatorsIndexRouteImport
      parentRoute: typeof EthereumValidatorsRoute
    }
    '/ethereum/slots/': {
      id: '/ethereum/slots/'
      path: '/'
      fullPath: '/ethereum/slots/'
      preLoaderRoute: typeof EthereumSlotsIndexRouteImport
      parentRoute: typeof EthereumSlotsRoute
    }
    '/ethereum/forks/': {
      id: '/ethereum/forks/'
      path: '/'
      fullPath: '/ethereum/forks/'
      preLoaderRoute: typeof EthereumForksIndexRouteImport
      parentRoute: typeof EthereumForksRoute
    }
    '/ethereum/epochs/': {
      id: '/ethereum/epochs/'
      path: '/'
      fullPath: '/ethereum/epochs/'
      preLoaderRoute: typeof EthereumEpochsIndexRouteImport
      parentRoute: typeof EthereumEpochsRoute
    }
    '/ethereum/entities/': {
      id: '/ethereum/entities/'
      path: '/'
      fullPath: '/ethereum/entities/'
      preLoaderRoute: typeof EthereumEntitiesIndexRouteImport
      parentRoute: typeof EthereumEntitiesRoute
    }
    '/ethereum/contracts/': {
      id: '/ethereum/contracts/'
      path: '/'
      fullPath: '/ethereum/contracts/'
      preLoaderRoute: typeof EthereumContractsIndexRouteImport
      parentRoute: typeof EthereumContractsRoute
    }
    '/xatu/contributors/$id': {
      id: '/xatu/contributors/$id'
      path: '/$id'
      fullPath: '/xatu/contributors/$id'
      preLoaderRoute: typeof XatuContributorsIdRouteImport
      parentRoute: typeof XatuContributorsRoute
    }
    '/ethereum/slots/$slot': {
      id: '/ethereum/slots/$slot'
      path: '/$slot'
      fullPath: '/ethereum/slots/$slot'
      preLoaderRoute: typeof EthereumSlotsSlotRouteImport
      parentRoute: typeof EthereumSlotsRoute
    }
    '/ethereum/forks/$fork': {
      id: '/ethereum/forks/$fork'
      path: '/$fork'
      fullPath: '/ethereum/forks/$fork'
      preLoaderRoute: typeof EthereumForksForkRouteImport
      parentRoute: typeof EthereumForksRoute
    }
    '/ethereum/execution/timings': {
      id: '/ethereum/execution/timings'
      path: '/timings'
      fullPath: '/ethereum/execution/timings'
      preLoaderRoute: typeof EthereumExecutionTimingsRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/execution/state-growth': {
      id: '/ethereum/execution/state-growth'
      path: '/state-growth'
      fullPath: '/ethereum/execution/state-growth'
      preLoaderRoute: typeof EthereumExecutionStateGrowthRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/execution/state-expiry': {
      id: '/ethereum/execution/state-expiry'
      path: '/state-expiry'
      fullPath: '/ethereum/execution/state-expiry'
      preLoaderRoute: typeof EthereumExecutionStateExpiryRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/execution/payloads': {
      id: '/ethereum/execution/payloads'
      path: '/payloads'
      fullPath: '/ethereum/execution/payloads'
      preLoaderRoute: typeof EthereumExecutionPayloadsRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/execution/overview': {
      id: '/ethereum/execution/overview'
      path: '/overview'
      fullPath: '/ethereum/execution/overview'
      preLoaderRoute: typeof EthereumExecutionOverviewRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/execution/gas-profiler': {
      id: '/ethereum/execution/gas-profiler'
      path: '/gas-profiler'
      fullPath: '/ethereum/execution/gas-profiler'
      preLoaderRoute: typeof EthereumExecutionGasProfilerRouteImport
      parentRoute: typeof EthereumExecutionRoute
    }
    '/ethereum/epochs/$epoch': {
      id: '/ethereum/epochs/$epoch'
      path: '/$epoch'
      fullPath: '/ethereum/epochs/$epoch'
      preLoaderRoute: typeof EthereumEpochsEpochRouteImport
      parentRoute: typeof EthereumEpochsRoute
    }
    '/ethereum/entities/$entity': {
      id: '/ethereum/entities/$entity'
      path: '/$entity'
      fullPath: '/ethereum/entities/$entity'
      preLoaderRoute: typeof EthereumEntitiesEntityRouteImport
      parentRoute: typeof EthereumEntitiesRoute
    }
    '/ethereum/data-availability/probes': {
      id: '/ethereum/data-availability/probes'
      path: '/probes'
      fullPath: '/ethereum/data-availability/probes'
      preLoaderRoute: typeof EthereumDataAvailabilityProbesRouteImport
      parentRoute: typeof EthereumDataAvailabilityRoute
    }
    '/ethereum/data-availability/custody': {
      id: '/ethereum/data-availability/custody'
      path: '/custody'
      fullPath: '/ethereum/data-availability/custody'
      preLoaderRoute: typeof EthereumDataAvailabilityCustodyRouteImport
      parentRoute: typeof EthereumDataAvailabilityRoute
    }
    '/ethereum/contracts/$address': {
      id: '/ethereum/contracts/$address'
      path: '/$address'
      fullPath: '/ethereum/contracts/$address'
      preLoaderRoute: typeof EthereumContractsAddressRouteImport
      parentRoute: typeof EthereumContractsRoute
    }
    '/ethereum/consensus/overview': {
      id: '/ethereum/consensus/overview'
      path: '/overview'
      fullPath: '/ethereum/consensus/overview'
      preLoaderRoute: typeof EthereumConsensusOverviewRouteImport
      parentRoute: typeof EthereumConsensusRoute
    }
    '/ethereum/consensus/fast-confirmation': {
      id: '/ethereum/consensus/fast-confirmation'
      path: '/fast-confirmation'
      fullPath: '/ethereum/consensus/fast-confirmation'
      preLoaderRoute: typeof EthereumConsensusFastConfirmationRouteImport
      parentRoute: typeof EthereumConsensusRoute
    }
    '/beacon/slot/live': {
      id: '/beacon/slot/live'
      path: '/beacon/slot/live'
      fullPath: '/beacon/slot/live'
      preLoaderRoute: typeof BeaconSlotLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beacon/block-production/live': {
      id: '/beacon/block-production/live'
      path: '/beacon/block-production/live'
      fullPath: '/beacon/block-production/live'
      preLoaderRoute: typeof BeaconBlockProductionLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethereum/execution/timings/': {
      id: '/ethereum/execution/timings/'
      path: '/'
      fullPath: '/ethereum/execution/timings/'
      preLoaderRoute: typeof EthereumExecutionTimingsIndexRouteImport
      parentRoute: typeof EthereumExecutionTimingsRoute
    }
    '/ethereum/execution/payloads/': {
      id: '/ethereum/execution/payloads/'
      path: '/'
      fullPath: '/ethereum/execution/payloads/'
      preLoaderRoute: typeof EthereumExecutionPayloadsIndexRouteImport
      parentRoute: typeof EthereumExecutionPayloadsRoute
    }
    '/ethereum/execution/gas-profiler/': {
      id: '/ethereum/execution/gas-profiler/'
      path: '/'
      fullPath: '/ethereum/execution/gas-profiler/'
      preLoaderRoute: typeof EthereumExecutionGasProfilerIndexRouteImport
      parentRoute: typeof EthereumExecutionGasProfilerRoute
    }
    '/ethereum/data-availability/probes/': {
      id: '/ethereum/data-availability/probes/'
      path: '/'
      fullPath: '/ethereum/data-availability/probes/'
      preLoaderRoute: typeof EthereumDataAvailabilityProbesIndexRouteImport
      parentRoute: typeof EthereumDataAvailabilityProbesRoute
    }
    '/ethereum/data-availability/custody/': {
      id: '/ethereum/data-availability/custody/'
      path: '/'
      fullPath: '/ethereum/data-availability/custody/'
      preLoaderRoute: typeof EthereumDataAvailabilityCustodyIndexRouteImport
      parentRoute: typeof EthereumDataAvailabilityCustodyRoute
    }
    '/ethereum/execution/gas-profiler/simulate': {
      id: '/ethereum/execution/gas-profiler/simulate'
      path: '/simulate'
      fullPath: '/ethereum/execution/gas-profiler/simulate'
      preLoaderRoute: typeof EthereumExecutionGasProfilerSimulateRouteImport
      parentRoute: typeof EthereumExecutionGasProfilerRoute
    }
    '/ethereum/execution/gas-profiler/tx/$txHash': {
      id: '/ethereum/execution/gas-profiler/tx/$txHash'
      path: '/tx/$txHash'
      fullPath: '/ethereum/execution/gas-profiler/tx/$txHash'
      preLoaderRoute: typeof EthereumExecutionGasProfilerTxTxHashRouteImport
      parentRoute: typeof EthereumExecutionGasProfilerRoute
    }
    '/ethereum/execution/gas-profiler/block/$blockNumber': {
      id: '/ethereum/execution/gas-profiler/block/$blockNumber'
      path: '/block/$blockNumber'
      fullPath: '/ethereum/execution/gas-profiler/block/$blockNumber'
      preLoaderRoute: typeof EthereumExecutionGasProfilerBlockBlockNumberRouteImport
      parentRoute: typeof EthereumExecutionGasProfilerRoute
    }
    '/ethereum/execution/gas-profiler/tx/$txHash_/call/$callId': {
      id: '/ethereum/execution/gas-profiler/tx/$txHash_/call/$callId'
      path: '/tx/$txHash/call/$callId'
      fullPath: '/ethereum/execution/gas-profiler/tx/$txHash/call/$callId'
      preLoaderRoute: typeof EthereumExecutionGasProfilerTxTxHashCallCallIdRouteImport
      parentRoute: typeof EthereumExecutionGasProfilerRoute
    }
  }
}

interface EthereumConsensusRouteChildren {
  EthereumConsensusFastConfirmationRoute: typeof EthereumConsensusFastConfirmationRoute
  EthereumConsensusOverviewRoute: typeof EthereumConsensusOverviewRoute
}

const EthereumConsensusRouteChildren: EthereumConsensusRouteChildren = {
  EthereumConsensusFastConfirmationRoute:
    EthereumConsensusFastConfirmationRoute,
  EthereumConsensusOverviewRoute: EthereumConsensusOverviewRoute,
}

const EthereumConsensusRouteWithChildren =
  EthereumConsensusRoute._addFileChildren(EthereumConsensusRouteChildren)

interface EthereumContractsRouteChildren {
  EthereumContractsAddressRoute: typeof EthereumContractsAddressRoute
  EthereumContractsIndexRoute: typeof EthereumContractsIndexRoute
}

const EthereumContractsRouteChildren: EthereumContractsRouteChildren = {
  EthereumContractsAddressRoute: EthereumContractsAddressRoute,
  EthereumContractsIndexRoute: EthereumContractsIndexRoute,
}

const EthereumContractsRouteWithChildren =
  EthereumContractsRoute._addFileChildren(EthereumContractsRouteChildren)

interface EthereumDataAvailabilityCustodyRouteChildren {
  EthereumDataAvailabilityCustodyIndexRoute: typeof EthereumDataAvailabilityCustodyIndexRoute
}

const EthereumDataAvailabilityCustodyRouteChildren: EthereumDataAvailabilityCustodyRouteChildren =
  {
    EthereumDataAvailabilityCustodyIndexRoute:
      EthereumDataAvailabilityCustodyIndexRoute,
  }

const EthereumDataAvailabilityCustodyRouteWithChildren =
  EthereumDataAvailabilityCustodyRoute._addFileChildren(
    EthereumDataAvailabilityCustodyRouteChildren,
  )

interface EthereumDataAvailabilityProbesRouteChildren {
  EthereumDataAvailabilityProbesIndexRoute: typeof EthereumDataAvailabilityProbesIndexRoute
}

const EthereumDataAvailabilityProbesRouteChildren: EthereumDataAvailabilityProbesRouteChildren =
  {
    EthereumDataAvailabilityProbesIndexRoute:
      EthereumDataAvailabilityProbesIndexRoute,
  }

const EthereumDataAvailabilityProbesRouteWithChildren =
  EthereumDataAvailabilityProbesRoute._addFileChildren(
    EthereumDataAvailabilityProbesRouteChildren,
  )

interface EthereumDataAvailabilityRouteChildren {
  EthereumDataAvailabilityCustodyRoute: typeof EthereumDataAvailabilityCustodyRouteWithChildren
  EthereumDataAvailabilityProbesRoute: typeof EthereumDataAvailabilityProbesRouteWithChildren
}

const EthereumDataAvailabilityRouteChildren: EthereumDataAvailabilityRouteChildren =
  {
    EthereumDataAvailabilityCustodyRoute:
      EthereumDataAvailabilityCustodyRouteWithChildren,
    EthereumDataAvailabilityProbesRoute:
      EthereumDataAvailabilityProbesRouteWithChildren,
  }

const EthereumDataAvailabilityRouteWithChildren =
  EthereumDataAvailabilityRoute._addFileChildren(
    EthereumDataAvailabilityRouteChildren,
  )

interface EthereumEntitiesRouteChildren {
  EthereumEntitiesEntityRoute: typeof EthereumEntitiesEntityRoute
  EthereumEntitiesIndexRoute: typeof EthereumEntitiesIndexRoute
}

const EthereumEntitiesRouteChildren: EthereumEntitiesRouteChildren = {
  EthereumEntitiesEntityRoute: EthereumEntitiesEntityRoute,
  EthereumEntitiesIndexRoute: EthereumEntitiesIndexRoute,
}

const EthereumEntitiesRouteWithChildren =
  EthereumEntitiesRoute._addFileChildren(EthereumEntitiesRouteChildren)

interface EthereumEpochsRouteChildren {
  EthereumEpochsEpochRoute: typeof EthereumEpochsEpochRoute
  EthereumEpochsIndexRoute: typeof EthereumEpochsIndexRoute
}

const EthereumEpochsRouteChildren: EthereumEpochsRouteChildren = {
  EthereumEpochsEpochRoute: EthereumEpochsEpochRoute,
  EthereumEpochsIndexRoute: EthereumEpochsIndexRoute,
}

const EthereumEpochsRouteWithChildren = EthereumEpochsRoute._addFileChildren(
  EthereumEpochsRouteChildren,
)

interface EthereumExecutionGasProfilerRouteChildren {
  EthereumExecutionGasProfilerSimulateRoute: typeof EthereumExecutionGasProfilerSimulateRoute
  EthereumExecutionGasProfilerIndexRoute: typeof EthereumExecutionGasProfilerIndexRoute
  EthereumExecutionGasProfilerBlockBlockNumberRoute: typeof EthereumExecutionGasProfilerBlockBlockNumberRoute
  EthereumExecutionGasProfilerTxTxHashRoute: typeof EthereumExecutionGasProfilerTxTxHashRoute
  EthereumExecutionGasProfilerTxTxHashCallCallIdRoute: typeof EthereumExecutionGasProfilerTxTxHashCallCallIdRoute
}

const EthereumExecutionGasProfilerRouteChildren: EthereumExecutionGasProfilerRouteChildren =
  {
    EthereumExecutionGasProfilerSimulateRoute:
      EthereumExecutionGasProfilerSimulateRoute,
    EthereumExecutionGasProfilerIndexRoute:
      EthereumExecutionGasProfilerIndexRoute,
    EthereumExecutionGasProfilerBlockBlockNumberRoute:
      EthereumExecutionGasProfilerBlockBlockNumberRoute,
    EthereumExecutionGasProfilerTxTxHashRoute:
      EthereumExecutionGasProfilerTxTxHashRoute,
    EthereumExecutionGasProfilerTxTxHashCallCallIdRoute:
      EthereumExecutionGasProfilerTxTxHashCallCallIdRoute,
  }

const EthereumExecutionGasProfilerRouteWithChildren =
  EthereumExecutionGasProfilerRoute._addFileChildren(
    EthereumExecutionGasProfilerRouteChildren,
  )

interface EthereumExecutionPayloadsRouteChildren {
  EthereumExecutionPayloadsIndexRoute: typeof EthereumExecutionPayloadsIndexRoute
}

const EthereumExecutionPayloadsRouteChildren: EthereumExecutionPayloadsRouteChildren =
  {
    EthereumExecutionPayloadsIndexRoute: EthereumExecutionPayloadsIndexRoute,
  }

const EthereumExecutionPayloadsRouteWithChildren =
  EthereumExecutionPayloadsRoute._addFileChildren(
    EthereumExecutionPayloadsRouteChildren,
  )

interface EthereumExecutionTimingsRouteChildren {
  EthereumExecutionTimingsIndexRoute: typeof EthereumExecutionTimingsIndexRoute
}

const EthereumExecutionTimingsRouteChildren: EthereumExecutionTimingsRouteChildren =
  {
    EthereumExecutionTimingsIndexRoute: EthereumExecutionTimingsIndexRoute,
  }

const EthereumExecutionTimingsRouteWithChildren =
  EthereumExecutionTimingsRoute._addFileChildren(
    EthereumExecutionTimingsRouteChildren,
  )

interface EthereumExecutionRouteChildren {
  EthereumExecutionGasProfilerRoute: typeof EthereumExecutionGasProfilerRouteWithChildren
  EthereumExecutionOverviewRoute: typeof EthereumExecutionOverviewRoute
  EthereumExecutionPayloadsRoute: typeof EthereumExecutionPayloadsRouteWithChildren
  EthereumExecutionStateExpiryRoute: typeof EthereumExecutionStateExpiryRoute
  EthereumExecutionStateGrowthRoute: typeof EthereumExecutionStateGrowthRoute
  EthereumExecutionTimingsRoute: typeof EthereumExecutionTimingsRouteWithChildren
}

const EthereumExecutionRouteChildren: EthereumExecutionRouteChildren = {
  EthereumExecutionGasProfilerRoute:
    EthereumExecutionGasProfilerRouteWithChildren,
  EthereumExecutionOverviewRoute: EthereumExecutionOverviewRoute,
  EthereumExecutionPayloadsRoute: EthereumExecutionPayloadsRouteWithChildren,
  EthereumExecutionStateExpiryRoute: EthereumExecutionStateExpiryRoute,
  EthereumExecutionStateGrowthRoute: EthereumExecutionStateGrowthRoute,
  EthereumExecutionTimingsRoute: EthereumExecutionTimingsRouteWithChildren,
}

const EthereumExecutionRouteWithChildren =
  EthereumExecutionRoute._addFileChildren(EthereumExecutionRouteChildren)

interface EthereumForksRouteChildren {
  EthereumForksForkRoute: typeof EthereumForksForkRoute
  EthereumForksIndexRoute: typeof EthereumForksIndexRoute
}

const EthereumForksRouteChildren: EthereumForksRouteChildren = {
  EthereumForksForkRoute: EthereumForksForkRoute,
  EthereumForksIndexRoute: EthereumForksIndexRoute,
}

const EthereumForksRouteWithChildren = EthereumForksRoute._addFileChildren(
  EthereumForksRouteChildren,
)

interface EthereumSlotsRouteChildren {
  EthereumSlotsSlotRoute: typeof EthereumSlotsSlotRoute
  EthereumSlotsIndexRoute: typeof EthereumSlotsIndexRoute
}

const EthereumSlotsRouteChildren: EthereumSlotsRouteChildren = {
  EthereumSlotsSlotRoute: EthereumSlotsSlotRoute,
  EthereumSlotsIndexRoute: EthereumSlotsIndexRoute,
}

const EthereumSlotsRouteWithChildren = EthereumSlotsRoute._addFileChildren(
  EthereumSlotsRouteChildren,
)

interface EthereumValidatorsRouteChildren {
  EthereumValidatorsIndexRoute: typeof EthereumValidatorsIndexRoute
}

const EthereumValidatorsRouteChildren: EthereumValidatorsRouteChildren = {
  EthereumValidatorsIndexRoute: EthereumValidatorsIndexRoute,
}

const EthereumValidatorsRouteWithChildren =
  EthereumValidatorsRoute._addFileChildren(EthereumValidatorsRouteChildren)

interface EthereumRouteChildren {
  EthereumConsensusRoute: typeof EthereumConsensusRouteWithChildren
  EthereumContractsRoute: typeof EthereumContractsRouteWithChildren
  EthereumDataAvailabilityRoute: typeof EthereumDataAvailabilityRouteWithChildren
  EthereumEntitiesRoute: typeof EthereumEntitiesRouteWithChildren
  EthereumEpochsRoute: typeof EthereumEpochsRouteWithChildren
  EthereumExecutionRoute: typeof EthereumExecutionRouteWithChildren
  EthereumForksRoute: typeof EthereumForksRouteWithChildren
  EthereumLiveRoute: typeof EthereumLiveRoute
  EthereumSlotsRoute: typeof EthereumSlotsRouteWithChildren
  EthereumValidatorsRoute: typeof EthereumValidatorsRouteWithChildren
}

const EthereumRouteChildren: EthereumRouteChildren = {
  EthereumConsensusRoute: EthereumConsensusRouteWithChildren,
  EthereumContractsRoute: EthereumContractsRouteWithChildren,
  EthereumDataAvailabilityRoute: EthereumDataAvailabilityRouteWithChildren,
  EthereumEntitiesRoute: EthereumEntitiesRouteWithChildren,
  EthereumEpochsRoute: EthereumEpochsRouteWithChildren,
  EthereumExecutionRoute: EthereumExecutionRouteWithChildren,
  EthereumForksRoute: EthereumForksRouteWithChildren,
  EthereumLiveRoute: EthereumLiveRoute,
  EthereumSlotsRoute: EthereumSlotsRouteWithChildren,
  EthereumValidatorsRoute: EthereumValidatorsRouteWithChildren,
}

const EthereumRouteWithChildren = EthereumRoute._addFileChildren(
  EthereumRouteChildren,
)

interface ExperimentsRouteChildren {
  ExperimentsBlockProductionFlowRoute: typeof ExperimentsBlockProductionFlowRoute
  ExperimentsLiveSlotsRoute: typeof ExperimentsLiveSlotsRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsBlockProductionFlowRoute: ExperimentsBlockProductionFlowRoute,
  ExperimentsLiveSlotsRoute: ExperimentsLiveSlotsRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

interface XatuContributorsRouteChildren {
  XatuContributorsIdRoute: typeof XatuContributorsIdRoute
  XatuContributorsIndexRoute: typeof XatuContributorsIndexRoute
}

const XatuContributorsRouteChildren: XatuContributorsRouteChildren = {
  XatuContributorsIdRoute: XatuContributorsIdRoute,
  XatuContributorsIndexRoute: XatuContributorsIndexRoute,
}

const XatuContributorsRouteWithChildren =
  XatuContributorsRoute._addFileChildren(XatuContributorsRouteChildren)

interface XatuRouteChildren {
  XatuContributorsRoute: typeof XatuContributorsRouteWithChildren
  XatuForkReadinessRoute: typeof XatuForkReadinessRoute
  XatuGeographicalChecklistRoute: typeof XatuGeographicalChecklistRoute
  XatuLocallyBuiltBlocksRoute: typeof XatuLocallyBuiltBlocksRoute
}

const XatuRouteChildren: XatuRouteChildren = {
  XatuContributorsRoute: XatuContributorsRouteWithChildren,
  XatuForkReadinessRoute: XatuForkReadinessRoute,
  XatuGeographicalChecklistRoute: XatuGeographicalChecklistRoute,
  XatuLocallyBuiltBlocksRoute: XatuLocallyBuiltBlocksRoute,
}

const XatuRouteWithChildren = XatuRoute._addFileChildren(XatuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EthereumRoute: EthereumRouteWithChildren,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  XatuRoute: XatuRouteWithChildren,
  BeaconLocallyBuiltBlocksRoute: BeaconLocallyBuiltBlocksRoute,
  XatuDataForkReadinessRoute: XatuDataForkReadinessRoute,
  XatuDataGeographicalChecklistRoute: XatuDataGeographicalChecklistRoute,
  XatuDataIndexRoute: XatuDataIndexRoute,
  BeaconBlockProductionLiveRoute: BeaconBlockProductionLiveRoute,
  BeaconSlotLiveRoute: BeaconSlotLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
